name: ep2
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2025.12.2=h06a4308_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.1.0=h2733197_1
  - libuv=1.48.0=h5eee18b_0
  - libwebp=1.2.0=h89dd481_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.5=h7934f7d_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openssl=3.0.17=h5eee18b_0
  - pillow=9.3.0=py38hace64e9_1
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.4.9=haebb681_0
  - pip:
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - anyio==4.5.2
    - asgiref==3.8.1
    - asttokens==3.0.1
    - attrs==25.3.0
    - backcall==0.2.0
    - backoff==2.2.1
    - bcrypt==5.0.0
    - beautifulsoup4==4.14.3
    - bleach==6.1.0
    - build==1.2.2.post1
    - cachetools==5.5.2
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - chroma-hnswlib==0.7.6
    - chromadb==0.5.23
    - click==8.1.8
    - coloredlogs==15.0.1
    - decorator==5.2.1
    - defusedxml==0.7.1
    - deprecated==1.3.1
    - distro==1.9.0
    - docopt==0.6.2
    - durationpy==0.10
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fastapi==0.124.4
    - fastjsonschema==2.21.2
    - filelock==3.16.1
    - flatbuffers==25.9.23
    - fsspec==2025.3.0
    - ftfy==6.2.3
    - google-auth==2.43.0
    - googleapis-common-protos==1.72.0
    - graphlib-backport==1.1.0
    - grpcio==1.70.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - humanfriendly==10.0
    - idna==3.11
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipython==8.12.3
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.3
    - jupyter-core==5.8.1
    - jupyterlab-pygments==0.3.0
    - kubernetes==34.1.0
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistune==3.1.4
    - mmh3==5.0.1
    - monotonic==1.6
    - mpmath==1.3.0
    - nbclient==0.10.1
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - networkx==3.1
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.3.1
    - onnxruntime==1.19.2
    - opentelemetry-api==1.33.1
    - opentelemetry-exporter-otlp-proto-common==1.33.1
    - opentelemetry-exporter-otlp-proto-grpc==1.33.1
    - opentelemetry-instrumentation==0.54b1
    - opentelemetry-instrumentation-asgi==0.54b1
    - opentelemetry-instrumentation-fastapi==0.54b1
    - opentelemetry-proto==1.33.1
    - opentelemetry-sdk==1.33.1
    - opentelemetry-semantic-conventions==0.54b1
    - opentelemetry-util-http==0.54b1
    - orjson==3.10.15
    - overrides==7.7.0
    - packaging==25.0
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pipreqs==0.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - posthog==2.5.0
    - prompt-toolkit==3.0.52
    - protobuf==5.29.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pygments==2.19.2
    - pymupdf==1.24.11
    - pypika==0.48.9
    - pyproject-hooks==1.2.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.4
    - requests-oauthlib==2.0.0
    - rich==14.2.0
    - rpds-py==0.20.1
    - rsa==4.9.1
    - safetensors==0.5.3
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - sentence-transformers==3.2.1
    - shellingham==1.5.4
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.7
    - stack-data==0.6.3
    - starlette==0.44.0
    - sympy==1.13.3
    - tenacity==9.0.0
    - threadpoolctl==3.5.0
    - tinycss2==1.2.1
    - tokenizers==0.20.3
    - tomli==2.3.0
    - torch==2.4.1+cpu
    - torchaudio==2.4.1+cpu
    - torchvision==0.19.1+cpu
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.46.3
    - triton==3.0.0
    - typer==0.20.0
    - typing-extensions==4.13.2
    - urllib3==2.2.3
    - uvicorn==0.33.0
    - uvloop==0.22.1
    - watchfiles==0.24.0
    - wcwidth==0.2.14
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - websockets==13.1
    - wrapt==1.17.3
    - yarg==0.1.9
    - zipp==3.20.2
prefix: /root/miniconda3/envs/ep2
